image_server: test配置的image_server

database-type: mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://158.101.8.192:3306/zhang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    username: avbjxwvp:avbjxwvp
    password: mEEmPE3K41WkR4T1YDaCUGSqI1SEww4S
    host: barnacle.rmq.cloudamqp.com
    port: 1883
    virtual-host: avbjxwvp