server:
  port: 8080
  servlet:
    context-path: /console
spring:
  profiles:
    active: test
  http:
    encoding:
      force: true
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog-master.xml
