server:
  port: 8080
  servlet:
    context-path: /console
spring:
  profiles:
    active: test
  http:
    encoding:
      force: true
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog-master.xml
  redis:
    database: 0
    host:
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

properties:
  server_dataCenterId: 1
  server_machineId: 1
  qiNiu_AccessKey: kp2FKD8lWEYVwnkni-h-4LUSRQ7LrEdiIh16nrmb
  qiNiu_SecretKey: qVHAoWFNYC0wJTy7vA_a8GxUI-fkBlCQfmS355tB
  image: image
  video: video
  imagePath: http://omjgaayha.bkt.clouddn.com


