image_server: test配置的image_server

database-type: mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.158.236:3306/zhang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    username: admin
    password: 123456
    host: 47.103.158.236
    port: 5672
